### ISSUE TITLE
[plugin-parcel] Unexpected token: punc (.)

### ISSUE THREAD

**Issue by iainnicol** [pikapkg/create-snowpack-app#121]
### Steps to reproduce

Using create-snowpack-app v1.1.1. In the terminal:

```
npx create-snowpack-app parcel-bug-example --template "@snowpack/app-template-react"
cd parcel-bug-example
npm add "@snowpack/plugin-parcel"
```
At this point, manually change ``snowpack.config.json`` so that plugins reads:

```
"plugins": ["@snowpack/plugin-parcel"]
```

Finally, back in the terminal, run:
```
npx snowpack build
```

### Actual output

```
  bundle:*................[FAIL] (plugin) @snowpack/plugin-parcel

▼ bundle:*

  ×  C:\git\snowpack-bug\parcel-bug-example\.build\_dist_\index.js: Unexpected token: punc (.)
      at Z.get (C:\git\snowpack-bug\parcel-bug-example\node_modules\terser\dist\bundle.min.js:1:525)
      at Object.errorToJson (C:\git\snowpack-bug\parcel-bug-example\node_modules\@parcel\utils\src\errorUtils.js:9:20)
      at Pipeline.process (C:\git\snowpack-bug\parcel-bug-example\node_modules\parcel-bundler\src\Pipeline.js:29:26)
  Error: Command failed with exit code 1: parcel build C:/git/snowpack-bug/parcel-bug-example/.build/index.html --out-dir C:\git\snowpack-bug\parcel-bug-example\build
  ×  C:\git\snowpack-bug\parcel-bug-example\.build\_dist_\index.js: Unexpected token: punc (.)
      at Z.get (C:\git\snowpack-bug\parcel-bug-example\node_modules\terser\dist\bundle.min.js:1:525)
      at Object.errorToJson (C:\git\snowpack-bug\parcel-bug-example\node_modules\@parcel\utils\src\errorUtils.js:9:20)
      at Pipeline.process (C:\git\snowpack-bug\parcel-bug-example\node_modules\parcel-bundler\src\Pipeline.js:29:26)
```

### Expected output

Parcel minifies the file project successfully.

Note that the webpack plugin seems to succeed, if used instead. Nonetheless, I don't know whether this is a snowpack issue or a parcel issue.

**Comment by hacktivist123** [comment]
@iainnicol  I also just encountered the same issue, webpack plugin works okay but parcel fails with the same error you posted

**Comment by FredKSchott** [comment]
It seems like Parcel v1 doesn't support `import.meta` & `import.meta.hot`, which is surprising. If I remove the HMR code in `src/index.js`, it works. 

We may need to add a warning to the Parcel plugin README until Parcel v2 is released

**Comment by hacktivist123** [comment]
Interesting, yeah adding it to the ReadME works.

**Comment by FredKSchott** [comment]
Added a note: https://github.com/pikapkg/create-snowpack-app/blob/master/packages/plugin-parcel/README.md
