### ISSUE TITLE
Snowpack install fails using React's template

### ISSUE THREAD

**Issue by charlyx** [pikapkg/create-snowpack-app#17]
Hello,

I've been willing to use `create-snowpack-app` with template `@snowpack/app-template-react` as such:
```
npx create-snowpack-app zenoid-web --template @snowpack/app-template-react --use-yarn
```

I'm using Node LTS (12.x) and I've also tried using `npm` instead of `yarn` but still get the following error:

```
$ snowpack
⠼ snowpack installing... https://cdn.pika.dev/-/csz@v1.2.0-kFAWghpicSRGKY3yxXZv/dist=es2019/csz.js
✘ /Users/charly/tmp/zenoid-web/node_modules/react/cjs/react.production.min.js?commonjs-proxy
👉 https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module

Error: '__moduleExports' is not exported by node_modules/react/cjs/react.production.min.js, imported by /Users/charly/tmp/zenoid-web/node_modules/react/cjs/react.production.min.js?commonjs-proxy
    at error (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:161:30)
    at Module.error (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:15006:16)
    at handleMissingExport (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:14905:28)
    at Module.traceVariable (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:15401:24)
    at ModuleScope.findVariable (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:13957:39)
    at Identifier$1.bind (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:9861:40)
    at ExportDefaultDeclaration.bind (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:9494:23)
    at Program$1.bind (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:9490:31)
    at Module.bindReferences (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:14978:18)
    at Graph.link (/Users/charly/tmp/zenoid-web/node_modules/rollup/dist/shared/rollup.js:18414:20)

error Command failed with exit code 1.
```

**Comment by FredKSchott** [comment]
Just released the fix and closed out the previous issue a few moments ago! Update Snowpack in your project or re-run `npx create-snowpack-app`

**Comment by charlyx** [comment]
Thanks a lot!
