### ISSUE TITLE
onboard validations to ensure that the respective package manager is installed

### ISSUE THREAD

**Issue by jamesgeorge007** [pikapkg/create-snowpack-app#170]
```sh
$ create-snowpack-app  --template @snowpack/app-template-react --use-pnpm --target <path>
  - Using template @snowpack/app-template-react
  - Creating a new project in <path>
  - Installing package dependencies. This might take a couple of minutes.

(node:21818) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: pnpm install --reporter=silent
spawn pnpm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:21818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:21818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jamesgeorge007** [comment]
This might not seem necessary, why would a user opt for a package manager that he/she doesn't have on his/her machine. But it is always good to have all the possible cases covered.

**Comment by FredKSchott** [comment]
I think this is tougher than it sounds, especially across MS, Mac, Linux. I'd prefer to not take on this complexity, but I would love to show a better, human-readable  error message here if it does not exist. Would you be interested in adding a PR for that?

**Comment by jamesgeorge007** [comment]
IMO a better idea would be to fall back and consume `npm` rather than exiting the process.

**Comment by FredKSchott** [comment]
In my experience, of the user is asking for something specific and you can’t deliver, it’s better to error and let them resolve. Too easy to miss what’s happened, otherwise.
