### ISSUE TITLE
create-snowpack-app fails to complete - Windows 10

### ISSUE THREAD

**Issue by austincrim** [pikapkg/create-snowpack-app#30]
I have tried to create an app with all the different templates but it always fails with the following output: 
```powershell
npx: installed 36 in 6.43s

  - Using template @snowpack/app-template-blank
  - Creating a new project in C:\repos\my-app
(node:3956) ExperimentalWarning: The fs.promises API is experimental
  - Installing package dependencies. This might take a couple of minutes.


> deasync@0.1.20 install C:\repos\my-app\node_modules\deasync
> node ./build.js

`win32-x64-node-10` exists; testing
Binary is fine; exiting

> core-js@2.6.11 postinstall C:\repos\my-app\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"


> parcel-bundler@1.12.4 postinstall C:\repos\my-app\node_modules\parcel-bundler
> node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"

Love Parcel? You can now donate to our open collective:
 > https://opencollective.com/parcel/donate

> undefined prepare C:\repos\my-app
> snowpack

(node:11924) ExperimentalWarning: The fs.promises API is experimental
\ snowpack installing... canvas-confetti
TypeError: zlib.brotliCompressSync is not a function
    at compareDependencies (C:\repos\my-app\node_modules\snowpack\dist-node\index.js:2370:22)
    at Object.writeBundle (C:\repos\my-app\node_modules\snowpack\dist-node\index.js:2409:7)
    at Promise.resolve.then (C:\repos\my-app\node_modules\rollup\dist\shared\rollup.js:18156:25)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined prepare: `snowpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the undefined prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\c097645\AppData\Roaming\npm-cache\_logs\2020-05-07T22_36_35_047Z-debug.log
(node:3956) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npm install --loglevel error
    at makeError (C:\Users\c097645\AppData\Roaming\npm-cache\_npx\3956\node_modules\create-snowpack-app\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\c097645\AppData\Roaming\npm-cache\_npx\3956\node_modules\create-snowpack-app\node_modules\execa\index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. ```

**Comment by FredKSchott** [comment]
Looks like you need to update to a later version of Node.js. We should check for this before running so that we can give a better error message!

**Comment by austincrim** [comment]
That was it, thank you for your quick response!

**Comment by FredKSchott** [comment]
Warning added in 1868a57
