### ISSUE TITLE
React template fails with a rollup error

### ISSUE THREAD

**Issue by Grafikart** [pikapkg/create-snowpack-app#8]
I just wanted to try snowpack for the first time and I chose the react template

```bash
npx create-snowpack-app prep-snowpack --template @snowpack/app-template-react
```

 and I got this error

```bash
⠸ snowpack installing... https://cdn.pika.dev/-/csz@v1.2.0-kFAWghpicSRGKY3yxXZv/dist=es2019/csz.js
✘ /prep-snowpack/node_modules/react/cjs/react.production.min.js?commonjs-proxy
👉 https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module

Error: '__moduleExports' is not exported by node_modules/react/cjs/react.production.min.js, imported by /prep-snowpack/node_modules/react/cjs/react.production.min.js?commonjs-proxy
    at error (/prep-snowpack/node_modules/rollup/dist/shared/rollup.js:161:30)
```

Other templates (svelte for instance) work as expected

## env

Node: 12.16.3
yarn : 1.19.0
npm : 6.14.4
OS: Arch Linux

**Comment by UnwrittenFun** [comment]
Getting the same thing, found a workaround is to move `react` and `react-dom` to the `webDependencies` section to let snowpack fully manage them.

My package.json now looks like this:
```json
{
  "scripts": {
    "prepare": "snowpack",
    "start": "snowpack dev",
    "build": "snowpack build --bundle",
    "test": "jest"
  },
  "webDependencies": {
    "csz": "^1.2.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0"
  },
  "devDependencies": {
    "@snowpack/app-scripts-react": "^0.2.4",
    "@testing-library/jest-dom": "^5.5.0",
    "@testing-library/react": "^10.0.3",
    "jest": "^25.4.0",
    "parcel-bundler": "^1.12.4",
    "snowpack": "^2.0.0-0",
    "typescript": "^3.8.0"
  }
}

```

**Comment by iBaldie** [comment]
I am getting a different error on Build and Dev:

```
Error: Cannot find module '/snowpack-react/web_modules/import-map.json'
Require stack:
- /snowpack-react/node_modules/snowpack/dist-node/index.js
- /snowpack-react/node_modules/snowpack/dist-node/index.bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at command$1 (/snowpack-react/node_modules/snowpack/dist-node/index.js:941:31)
    at cli (/snowpack-react/node_modules/snowpack/dist-node/index.js:3026:11)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `snowpack dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by FredKSchott** [comment]
Same bug as #11, will be fixed in the next release of Snowpack (out later today). Thanks for filing!
