### ISSUE TITLE
create-snowpack-app fails on git commit

### ISSUE THREAD

**Issue by ImVexed** [pikapkg/create-snowpack-app#81]
I don't have a global git `user.email` and `user.name` and due to this git prompts for it when commiting anything.

```
(node:21972) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 128: git commit -m initial commit

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '_@_.(none)')
    at makeError (C:\Users\_\AppData\Roaming\npm-cache\_npx\21972\node_modules\create-snowpack-app\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\_\AppData\Roaming\npm-cache\_npx\21972\node_modules\create-snowpack-app\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\_\AppData\Roaming\npm-cache\_npx\21972\node_modules\create-snowpack-app\index.js:152:3
(node:21972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by FredKSchott** [comment]
Thanks! Fixed in 53dd8cf
