### ISSUE TITLE
Command failed with exit code 243: npm install @snowpack/app-template-svelte

### ISSUE THREAD

**Issue by rondonjon** [pikapkg/create-snowpack-app#92]
Just wanted to give snowpack a first shot, but `create-snowpack-app` keeps failing:

```
user@home:~:^$ npx create-snowpack-app snowpack-test --template "@snowpack/app-template-svelte" --use-yarn --force
npx: Installierte 36 in 1.994s

  - Using template @snowpack/app-template-svelte
  - Creating a new project in /home/user/snowpack-test
(node:847187) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 243: npm install @snowpack/app-template-svelte --ignore-scripts
    at makeError (/home/user/.npm/_npx/847187/lib/node_modules/create-snowpack-app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/user/.npm/_npx/847187/lib/node_modules/create-snowpack-app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/user/.npm/_npx/847187/lib/node_modules/create-snowpack-app/index.js:127:3
(node:847187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:847187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

To my surprise, the failing command executes just fine when I execute it manually in the terminal:

```
user@home:~/testing:^$ npm install @snowpack/app-template-svelte --ignore-scripts
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/2776/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @babel/plugin-syntax-import-meta@7.10.1 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @rollup/plugin-commonjs@11.0.2 requires a peer of rollup@^1.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN testing No description
npm WARN testing No repository field.
npm WARN testing No license field.

+ @snowpack/app-template-svelte@1.0.2
added 22 packages from 3 contributors, removed 18 packages, updated 219 packages and audited 244 packages in 11.864s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Any suggestions?

Setup:

node: 12.17.0
npm: 6.14.4
yarn: 1.22.4
OS: GNU/Linux / x86_64 / 5.4.0-31-generic

**Comment by FredKSchott** [comment]
That is very strange. probably some temporary npm error, but just in case I've added fafb746 which should add reporting for the failed output so that you can see what happened.

**Comment by FredKSchott** [comment]
Thanks for filing!
